# Generated by Django 2.2 on 2019-04-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkpages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
